apiVersion: v1
kind: Service
metadata:
    name: keycloak
    labels:
        app: keycloak
spec:
    ports:
        - name: keycloak
          port: 8080
          targetPort: 8080
          nodePort: 30006
    selector:
        app: keycloak
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak
    labels:
        app: keycloak
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak
    template:
        metadata:
            labels:
                app: keycloak
        spec:
            containers:
                - name: keycloak
                  image: quay.io/keycloak/keycloak:22.0
                  args: ["start-dev"]
                  env:
                      - name: KEYCLOAK_ADMIN
                        value: "admin"
                      - name: KEYCLOAK_ADMIN_PASSWORD
                        value: "admin"
                      - name: KC_PROXY
                        value: "edge"
                      - name: KC_HOSTNAME
                        value: "keycloak.dratini.tech"
                      - name: KC_HOSTNAME_STRICT
                        value: "false"

                      - name: KC_DB
                        value: "postgres"
                      - name: POSTGRES_DB
                        value: "KEY_CLOAK"
                      - name: KC_DB_URL
                        value: "jdbc:postgresql://ssh.dratini.tech:5100/KEY_CLOAK"
                      - name: KC_DB_USERNAME
                        value: "admin"
                      - name: KC_DB_PASSWORD
                        value: "password"
                  ports:
                      - name: http
                        containerPort: 8080
                      - name: https
                        containerPort: 8443
                  readinessProbe:
                      httpGet:
                          path: /realms/master
                          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "keycloak"

spec:
    rules:
        - host: keycloak.dratini.tech
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: keycloak
                            port:
                                number: 8080
